packages:
  - 'apps/*'
  - 'packages/*'
  - 'turbo/*'

catalog:
  # 核心框架 (Core Framework)
  react: ^19.2.3
  'react-dom': ^19.2.3
  next: ^16.1.4

  # 开发工具 (Development Tools)
  typescript: ^5.9.3
  eslint: ^9.39.1
  '@eslint/js': ^9.39.1
  'eslint-config-next': ^16.1.4
  'eslint-config-prettier': ^10.1.8
  'eslint-plugin-only-warn': ^1.1.0
  'eslint-plugin-better-tailwindcss': ^4.0.1
  'eslint-plugin-turbo': ^2.5.5
  'prettier-plugin-tailwindcss': ^0.7.2
  husky: ^9.1.7
  'lint-staged': ^16.2.7
  '@commitlint/cli': ^20.3.1
  '@commitlint/config-conventional': ^20.3.1
  'babel-plugin-react-compiler': ^1.0.0

  # 类型定义 (Type Definitions)
  '@types/node': ^20.19.25
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3

  # UI 组件库 (UI Libraries)
  '@radix-ui/react-slot': ^1.2.3
  'next-themes': ^0.4.6

  # 样式工具 (Styling Tools)
  tailwindcss: ^4.1.18
  '@tailwindcss/postcss': ^4.1.18
  'tailwind-merge': ^3.4.0

  # 构建工具 (Build Tools)
  turbo: ^2.7.4
  '@turbo/gen': ^2.5.5
  prettier: ^3.7.4

  # 工具库 (Utility Libraries)
  'class-variance-authority': ^0.7.1
  clsx: ^2.1.1
  globals: ^15.15.0
  tw-animate-css: ^1.4.0
  'tailwindcss-animate': ^1.0.7

catalogMode: prefer

onlyBuiltDependencies:
  - core-js-pure
  - sharp
  - unrs-resolver
